# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  yaml_cpp_config = debug
  Walnut_Headless_config = debug
  Walnut_Networking_config = debug
  App_Common_Headless_config = debug
  App_Server_Headless_config = debug

else ifeq ($(config),release)
  yaml_cpp_config = release
  Walnut_Headless_config = release
  Walnut_Networking_config = release
  App_Common_Headless_config = release
  App_Server_Headless_config = release

else ifeq ($(config),dist)
  yaml_cpp_config = dist
  Walnut_Headless_config = dist
  Walnut_Networking_config = dist
  App_Common_Headless_config = dist
  App_Server_Headless_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := yaml-cpp Walnut-Headless Walnut-Networking App-Common-Headless App-Server-Headless

.PHONY: all clean help $(PROJECTS) App Core Dependencies

all: $(PROJECTS)

App: App-Common-Headless App-Server-Headless

Core: Walnut-Headless Walnut-Networking

Dependencies: yaml-cpp

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C Walnut/vendor/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

Walnut-Headless:
ifneq (,$(Walnut_Headless_config))
	@echo "==== Building Walnut-Headless ($(Walnut_Headless_config)) ===="
	@${MAKE} --no-print-directory -C Walnut/Walnut -f Makefile config=$(Walnut_Headless_config)
endif

Walnut-Networking:
ifneq (,$(Walnut_Networking_config))
	@echo "==== Building Walnut-Networking ($(Walnut_Networking_config)) ===="
	@${MAKE} --no-print-directory -C Walnut/Walnut-Modules/Walnut-Networking -f Makefile config=$(Walnut_Networking_config)
endif

App-Common-Headless: Walnut-Headless Walnut-Networking
ifneq (,$(App_Common_Headless_config))
	@echo "==== Building App-Common-Headless ($(App_Common_Headless_config)) ===="
	@${MAKE} --no-print-directory -C App-Common -f Makefile config=$(App_Common_Headless_config)
endif

App-Server-Headless: App-Common-Headless Walnut-Headless Walnut-Networking yaml-cpp
ifneq (,$(App_Server_Headless_config))
	@echo "==== Building App-Server-Headless ($(App_Server_Headless_config)) ===="
	@${MAKE} --no-print-directory -C App-Server -f Makefile config=$(App_Server_Headless_config)
endif

clean:
	@${MAKE} --no-print-directory -C Walnut/vendor/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C Walnut/Walnut -f Makefile clean
	@${MAKE} --no-print-directory -C Walnut/Walnut-Modules/Walnut-Networking -f Makefile clean
	@${MAKE} --no-print-directory -C App-Common -f Makefile clean
	@${MAKE} --no-print-directory -C App-Server -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   yaml-cpp"
	@echo "   Walnut-Headless"
	@echo "   Walnut-Networking"
	@echo "   App-Common-Headless"
	@echo "   App-Server-Headless"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"